spring.application.name=demo
spring.datasource.url=jdbc:postgresql://svc.sel3.cloudtype.app:32188/arpeggio
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://client-51ks.onrender.com}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true